name: create-patch

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Make
        run: |
          ./stat-dump results
          sudo apt install wormhole
          wormhole send results.tar.xz
  
