name: make

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install & config Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
          stable: true
          token: ${{ github.token }}
      - name: make all
        run: |
          make all
